version: '3'

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - my_network
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/html/wordpress/
    networks:
      - my_network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress/
    networks:
      - my_network
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/slaajour/data/mariadb/
      
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/slaajour/data/wordpress/

networks:
  my_network: