version: "3"

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - .env
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - wp_vl:/var/www/html
    image: wordpress:latest
    restart: always
    networks:
      - my_network

  mariadb:
    container_name: mariadb
    env_file:
      - ./.env
    restart: always
    networks:
      - my_network
    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - db_vl:/var/lib/mysql

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "9999:433"
    env_file:
      - .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wp_vl:/var/www/html
    networks:
      - my_network

volumes:
  wp_vl:
    driver: local
    driver_opts:
      type: none
      o: bind

  db_vl:
    driver: local
    driver_opts:
      type: none
      o: bind


networks:
  my_network:
    driver: bridge